// Copyright (c) Prometheus. Generated by scaffold-flutter-a2ui.sh.
//
// A2UI surface widget.
//
// Reads the store; never drives the renderer directly. This mirrors the web
// host's component/hook/store split, so the same layering rule holds on both
// platforms and a reviewer can check one against the other.
//
// Failure renders IN THE TREE, not just to the console. A widget test — and a
// user — can see a visible error; neither can see a log line.

import 'package:flutter/material.dart';
import 'package:genui/genui.dart';

import 'a2ui_surface_controller.dart';

/// Renders an A2UI surface from [store].
///
/// Pass [messages] to ingest a v1.0 document on first build, or drive
/// [store.ingest] yourself for a streaming source.
class A2uiSurfaceView extends StatefulWidget {
  const A2uiSurfaceView({
    super.key,
    required this.store,
    this.messages,
    this.actionDelegate = const DefaultActionDelegate(),
  });

  final A2uiSurfaceStore store;

  /// A2UI **v1.0** messages ingested once on init. Omit when the host feeds
  /// the store from a live source instead.
  final List<dynamic>? messages;

  /// Handles UI actions raised by rendered components.
  final ActionDelegate actionDelegate;

  @override
  State<A2uiSurfaceView> createState() => _A2uiSurfaceViewState();
}

class _A2uiSurfaceViewState extends State<A2uiSurfaceView> {
  @override
  void initState() {
    super.initState();
    final messages = widget.messages;
    if (messages != null) {
      widget.store.ingest(messages);
    }
  }

  @override
  Widget build(BuildContext context) {
    final store = widget.store;

    switch (store.status) {
      case A2uiStatus.idle:
      case A2uiStatus.loading:
        return const Center(
          child: Padding(
            padding: EdgeInsets.all(24),
            child: Text('Loading agent surface…'),
          ),
        );

      case A2uiStatus.error:
        // Visible, and semantically an alert — a silent failure inside a
        // generated surface is indistinguishable from an empty one.
        return Semantics(
          liveRegion: true,
          child: Padding(
            padding: const EdgeInsets.all(24),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              mainAxisSize: MainAxisSize.min,
              children: [
                Text(
                  'A2UI surface failed to render',
                  style: Theme.of(context).textTheme.titleMedium,
                ),
                const SizedBox(height: 8),
                Text(store.error ?? 'Unknown error.'),
              ],
            ),
          ),
        );

      case A2uiStatus.ready:
        final surfaceContext = store.surfaceContext;
        if (surfaceContext == null) {
          return const Padding(
            padding: EdgeInsets.all(24),
            child: Text('Surface is ready but has no context.'),
          );
        }
        return Surface(
          surfaceContext: surfaceContext,
          actionDelegate: widget.actionDelegate,
        );
    }
  }
}
