// Copyright (c) Prometheus. Generated by scaffold-flutter-a2ui.sh.
//
// A2UI v1.0 -> v0.9 translation.
//
// THIS FILE IS THE PARITY SEAM. The identical translation exists in two other
// places, and all three must agree or the surfaces drift apart:
//
//   web (AG-UI) : assets/scaffold/a2ui/a2ui-surface.tsx    toSdkMessages()
//   MCP-UI guest: assets/scaffold/mcp-ui/guest/…           toV09Messages()
//   Flutter     : this file                                 toV09Messages()
//
// Two differences between the versions, both structural:
//
//   1. CATALOG ID — a v1.0 document names the v1.0 catalog URL. The renderer
//      registers only its own v0.9 catalog and raises "Catalog not found" for
//      anything else, so the id is retargeted to `basicCatalogId`.
//
//   2. MESSAGE SPLIT — v1.0 carries `components` and `dataModel` INSIDE
//      `createSurface`. v0.9 expects three separate messages. Without the split
//      the surface is created but never populated: it renders empty, with no
//      error. That silence is why this translation is a named, tested seam
//      rather than an inline detail.
//
// The catalogId is a renderer-registration concern, not UI semantics — the
// components and data model pass through untouched, so the same v1.0 document
// produces the same UI on every surface.

import 'package:genui/genui.dart' show basicCatalogId;

/// Translate A2UI **v1.0** messages into what the pinned **v0.9** renderer
/// accepts. Messages that are not `createSurface` pass through unchanged.
List<Map<String, Object?>> toV09Messages(
  List<dynamic> messages, {
  String catalogId = basicCatalogId,
}) {
  final out = <Map<String, Object?>>[];
  for (final raw in messages) {
    if (raw is! Map) {
      continue;
    }
    final message = Map<String, dynamic>.from(raw);
    final createSurface = message['createSurface'];
    if (createSurface is! Map) {
      out.add(message);
      continue;
    }

    final surface = Map<String, dynamic>.from(createSurface);
    final surfaceId = surface['surfaceId'] as String?;
    if (surfaceId == null) {
      // A createSurface without an id cannot be split coherently. Pass it
      // through so the renderer reports it, rather than dropping it here.
      out.add(message);
      continue;
    }

    out.add({
      'version': 'v0.9',
      'createSurface': {'surfaceId': surfaceId, 'catalogId': catalogId},
    });

    final components = surface['components'];
    if (components is List && components.isNotEmpty) {
      out.add({
        'version': 'v0.9',
        'updateComponents': {'surfaceId': surfaceId, 'components': components},
      });
    }

    if (surface['dataModel'] != null) {
      out.add({
        'version': 'v0.9',
        'updateDataModel': {
          'surfaceId': surfaceId,
          'path': '/',
          'value': surface['dataModel'],
        },
      });
    }
  }
  return out;
}
