// Copyright (c) Prometheus. Generated by scaffold-flutter-a2ui.sh.
//
// CROSS-PLATFORM PARITY TEST.
//
// This is the test the `a2ui-surface-contract` skill asks for: "equivalent
// semantics across supported surfaces". It drives the SAME A2UI document the
// web host renders and asserts the SAME observable facts the web browser gate
// asserts — heading, body text, and two labelled buttons.
//
// It ships with the generated app rather than living only in the repo that
// wrote it, so a project inherits the check instead of trusting that parity
// held once, somewhere else.
//
// If this fails after a dependency bump, the surfaces have drifted. Fix the
// drift; do not relax the assertion.

import 'dart:convert';
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:__PACKAGE__/a2ui/a2ui_surface_controller.dart';
import 'package:__PACKAGE__/a2ui/a2ui_surface_widget.dart';

void main() {
  testWidgets('renders the shared A2UI document identically to the web host',
      (tester) async {
    final raw = File('assets/a2ui/source.a2ui.json').readAsStringSync();
    final document = jsonDecode(raw);

    final store = A2uiSurfaceStore();
    await tester.pumpWidget(
      MaterialApp(
        home: Scaffold(
          body: A2uiSurfaceView(store: store, messages: [document]),
        ),
      ),
    );
    await tester.pumpAndSettle();

    // The web host's browser gate asserts exactly these facts.
    expect(find.text('Enable notifications'), findsOneWidget,
        reason: 'heading from the shared A2UI document');
    expect(find.textContaining('Get alerts'), findsOneWidget,
        reason: 'body text from the shared A2UI document');

    final buttons = find.byWidgetPredicate((w) => w is ButtonStyleButton);
    expect(buttons, findsNWidgets(2),
        reason: 'two Button components, same as the web surface');
    expect(find.text('Enable'), findsOneWidget);
    expect(find.text('Not now'), findsOneWidget);
  });

  testWidgets('reports a malformed document visibly rather than rendering empty',
      (tester) async {
    final store = A2uiSurfaceStore();
    await tester.pumpWidget(
      MaterialApp(
        home: Scaffold(
          // No createSurface: the surface can never populate. An empty render
          // here would be indistinguishable from a working-but-blank surface,
          // which is the failure mode this asserts against.
          body: A2uiSurfaceView(store: store, messages: const [
            {'version': 'v1.0', 'updateDataModel': {'surfaceId': 'x'}}
          ]),
        ),
      ),
    );
    await tester.pumpAndSettle();

    expect(find.text('A2UI surface failed to render'), findsOneWidget);
  });
}
