// Copyright (c) Prometheus. Generated by scaffold-flutter-a2ui.sh.
//
// A2UI surface state for Flutter.
//
// Owns all A2UI message intake, mirroring the layering the web host uses
// (references/scaffolds/state-architecture.md): the store owns I/O, the widget
// reads it. Nothing here imports `material` — this layer is renderer-agnostic
// state, and keeping it widget-free is what makes it testable headlessly.
//
// The Flutter analogue of the web store:
//
//   web    : useSurfaceStore  ->  MessageProcessor([basicCatalog]).processMessages()
//   Flutter: A2uiSurfaceStore ->  SurfaceController(catalogs: […]).handleMessage()
//
// `SurfaceController` implements `A2uiMessageSink` and wraps
// `core.MessageProcessor` internally — the same class the web SDK uses, because
// both come from `a2ui-project/a2ui`.

import 'dart:async';

import 'package:a2ui_core/a2ui_core.dart' as core;
import 'package:genui/genui.dart';

import 'a2ui_translation.dart';

/// Lifecycle of a surface, matching the web store's status values so both
/// hosts report the same states.
enum A2uiStatus { idle, loading, ready, error }

/// Holds one A2UI surface and the controller that renders it.
class A2uiSurfaceStore {
  A2uiSurfaceStore({List<Catalog>? catalogs})
      : _controller = SurfaceController(
          catalogs: catalogs ?? [BasicCatalogItems.asCatalog()],
        );

  final SurfaceController _controller;

  A2uiStatus _status = A2uiStatus.idle;
  String? _surfaceId;
  String? _error;

  A2uiStatus get status => _status;
  String? get error => _error;
  String? get surfaceId => _surfaceId;

  /// The rendering context for the active surface, or null before one exists.
  /// `Surface` takes this directly.
  SurfaceContext? get surfaceContext =>
      _surfaceId == null ? null : _controller.contextFor(_surfaceId!);

  /// Surface lifecycle events, for a host that needs to react to them.
  Stream<SurfaceUpdate> get surfaceUpdates => _controller.surfaceUpdates;

  /// Feed A2UI **v1.0** messages. They are translated to v0.9 here — see
  /// `a2ui_translation.dart` for why that seam exists and where its twins are.
  ///
  /// Errors are captured rather than thrown: a malformed message from an agent
  /// is a runtime condition the UI must report, not a crash.
  void ingest(List<dynamic> messages) {
    _status = A2uiStatus.loading;
    _error = null;
    try {
      for (final message in toV09Messages(messages)) {
        _controller.handleMessage(core.A2uiMessage.fromJson(message));
        final created = message['createSurface'];
        if (created is Map && created['surfaceId'] is String) {
          _surfaceId = created['surfaceId'] as String;
        }
      }
      if (_surfaceId == null) {
        _status = A2uiStatus.error;
        _error = 'No createSurface message — nothing to render.';
        return;
      }
      _status = A2uiStatus.ready;
    } catch (err) {
      _status = A2uiStatus.error;
      _error = err.toString();
    }
  }

  void reset() {
    _status = A2uiStatus.idle;
    _surfaceId = null;
    _error = null;
  }
}
